version: '3.8'

services:
  mysql:
    container_name: db_mysql
    image: mysql/mysql-server:8.0
    volumes: 
      - ./db:/db
    restart: on-failure
    ports:
        - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
        - MYSQL_DATABASE=test